/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pokemon name and url
 */
export interface FetchPokemon { 
    /**
     * the name of the pokemon
     */
    name?: string;
    /**
     * the url of the pokemon
     */
    url?: string;
}

